name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - uses: dotnet/nbgv@master
      with:
        setAllVars: true

    - name: Build
      run: go build -ldflags "-X main.mainver=$env:NBGV_SimpleVersion" -v ./...

#     - name: Test
#       run: go test -v ./...

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: |
        gh release create v$NBGV_SimpleVersion certtools.exe
